### ISSUE TITLE
Replace raw metadata results in "Sorry something went wrong" screen.

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/mira#641]
Used the export function (all data streams) to export a metadata file and made a minor adjustment by removing the text "cataloguer fix me" from descriptions.  When I tried to use the replace metadata tool, I got the "Sorry something went wrong" screen.

**Comment by mark-dce** [comment]
@Alexandermay can you e-mail me a copy of the file you tried to import (or post it here in a comment if it's not too long)

**Comment by mark-dce** [comment]
Alex sent the file and I've saved it to google drive here:
https://drive.google.com/open?id=0BytolfRBVL3rLUxnbUFPMzdDeTQ&authuser=0  
or search for "633 batch_155.xml"

**Comment by mark-dce** [comment]
I just retried the import with Alex's file and get the following in the production.log

```text
I, [2015-06-22T15:36:21.956572 #31991]  INFO -- : Started POST "/batch/metadata_imports" for 97.116.187.88 at 2015-06-22 15:36:21 +0000
I, [2015-06-22T15:36:21.957734 #31991]  INFO -- : Processing by Batch::MetadataImportsController#create as HTML
I, [2015-06-22T15:36:21.957821 #31991]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"lPPPHjFd+STpFBRIOyAHqKK/RMZ7xT8uqTgjXPZpN4A=", "batch_metadata_import"=>{"metadata_file"=>#<ActionDispatch::Http::UploadedFile:0x007f665fbab770 @tempfile=#<Tempfile:/tmp/RackMultipart20150622-31991-1xrnhqk>, @original_filename="633 - batch_155.xml", @content_type="text/xml", @headers="Content-Disposition: form-data; name=\"batch_metadata_import[metadata_file]\"; filename=\"633 - batch_155.xml\"\r\nContent-Type: text/xml\r\n">}, "commit"=>"Next"}
D, [2015-06-22T15:36:21.958998 #31991] DEBUG -- :   User Load (0.1ms)  SELECT  `users`.* FROM `users`  WHERE `users`.`id` = 3  ORDER BY `users`.`id` ASC LIMIT 1
D, [2015-06-22T15:36:21.962893 #31991] DEBUG -- :   Role Load (0.1ms)  SELECT `roles`.* FROM `roles` INNER JOIN `roles_users` ON `roles`.`id` = `roles_users`.`role_id` WHERE `roles_users`.`user_id` = 3
D, [2015-06-22T15:36:21.963047 #31991] DEBUG -- : Usergroups are ["public", "admin", "registered"]
D, [2015-06-22T15:36:21.963819 #31991] DEBUG -- :   Role Exists (0.1ms)  SELECT  1 AS one FROM `roles` INNER JOIN `roles_users` ON `roles`.`id` = `roles_users`.`role_id` WHERE `roles_users`.`user_id` = 3 AND `roles`.`name` = 'admin' LIMIT 1
D, [2015-06-22T15:36:21.970877 #31991] DEBUG -- :    (0.1ms)  BEGIN
D, [2015-06-22T15:36:21.976052 #31991] DEBUG -- :   SQL (2.4ms)  INSERT INTO `batches` (`created_at`, `creator_id`, `job_ids`, `metadata_file`, `pids`, `type`) VALUES ('2015-06-22 15:36:21', 3, '--- []\n', '<?xml version=\"1.0\" encoding=\"UTF-8\"?><items><digitalObject><pid>draft:813</pid><datastream id=\"DCA-META\"><dc xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dcadesc=\"http://nils.lib.tufts.edu/dcadesc/\" xmlns:dcatech=\"http://nils.lib.tufts.edu/dcatech/\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"0.1\">\n  <dc:creator>Rowlandson, Thomas, 1756-1828.</dc:creator>\n  <dc:description>This engraving of an art exhibition in Somerset House was pub
```
[ looong contents of import file here ]

```text
<digitalObject><pid>draft:754</pid><datastream id=\"DCA-META\"><dc xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dcadesc=\"http://nils.lib.tufts.edu/dcadesc/\" xmlns:dcatech=\"http://nils.lib.tufts.edu/dcatech/\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"0.1\">\n  <dc:creator>Rigaud, Hyacinthe, 1659-1743.</dc:creator>\n  <dc:description>Portrait requested by King Louis XIV as a gift for his grandson, the future Philip V of Spain (r.1700-1746). Louis liked the portrait so much that he ordered a copy so that he could keep the original for himself.</dc:description>\n  <dc:description>Date Created: 1701.</dc:description>\n  <dc:description>Location created: Paris, France.</dc:description>\n  <dc:description>Current Location: Louvre Museum, Paris.</dc:description>\n  <dc:description>Medium: Oil on canvas.</dc:description>\n  <dc:description>Measurements: 9\'2 x7\'10 3/4\" (2.19 x2.4 m)</dc:description>\n  <dc:description>Accession Number: 14.8502-23AM.1</dc:description>\n  <dc:publisher>Tufts University. Tisch Library.</dc:publisher>\n  <dc:source>Artifact</dc:source>\n  <dc:date.created>1701</dc:date.created>\n  <dc:type>Image</dc:type>\n  <dc:format>image/tiff</dc:format>\n  <dcadesc:persname>Louis Le Grand. Sun King, 1638-1715. Louis XIV, King of France, 1638-1715.</dcadesc:persname>\n  <dcadesc:geogname>Versailles (France)</dcadesc:geogname>\n  <dcadesc:geogname>I&#x302;le-de-France (France)</dcadesc:geogname>\n  <dcadesc:subject>Portrait painting--18th century.</dcadesc:subject>\n  <dcadesc:subject>Portrait painting, European--18th century.</dcadesc:subject>\n  <dcadesc:subject>Portrait painting, French--18th century.</dcadesc:subject>\n  <dcadesc:subject>Royalty.</dcadesc:subject>\n  <dcadesc:subject>Kings and rulers--Portraits.</dcadesc:subject>\n  <dcadesc:subject>Painting, French--Baroque.</dcadesc:subject>\n  <dcadesc:genre>Portraits.</dcadesc:genre>\n  <dcadesc:genre>Royalty.</dcadesc:genre>\n  <dcadesc:genre>Baroque.</dcadesc:genre>\n  <dc:rights>http://sites.tufts.edu/dca/research-help/copyright-and-citations/</dc:rights>\n  <dc:temporal>17th century.</dc:temporal>\n  <dc:temporal>18th century.</dc:temporal>\n  <dc:title>Louis XIV.</dc:title>\n</dc></datastream><datastream id=\"DC-DETAIL-META\"><dc xmlns=\"http://purl.org/dc/elements/1.1/\" xmlns:dcadesc=\"http://nils.lib.tufts.edu/dcadesc/\" xmlns:dcatech=\"http://nils.lib.tufts.edu/dcatech/\" xmlns:dcterms=\"http://purl.org/d/terms/\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"0.1\">\n  <dcterms:abstract/>\n</dc></datastream><datastream id=\"DCA-ADMIN\"><admin xmlns:local=\"http://nils.lib.tufts.edu/dcaadmin/\" xmlns:ac=\"http://purl.org/dc/dcmitype/\">\n  <local:createdby>externalXSLT</local:createdby>\n  <local:steward>tisch</local:steward>\n  <ac:name>amay02</ac:name>\n  <ac:comment>ArtBatchTransform: 2015-06-18T14:26:31.118-04:00</ac:comment>\n  <local:displays>trove</local:displays>\n  <local:batchID>138</local:batchID>\n  <local:editedAt>2015-06-19T00:11:27Z</local:editedAt>\n<local:batchID>155</local:batchID></admin></datastream><datastream id=\"RELS-EXT\">\n<rdf:RDF xmlns:ns0=\"info:fedora/fedora-system:def/model#\" xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">\n  <rdf:Description rdf:about=\"info:fedora/draft:754\">\n    <ns0:hasModel rdf:resource=\"info:fedora/cm:Image.4DS\"></ns0:hasModel>\n  </rdf:Description>\n</rdf:RDF>\n</datastream></digitalObject></items>', '---\n- draft:813\n- draft:812\n- draft:811\n- draft:810\n- draft:809\n- draft:808\n- draft:807\n- draft:806\n- draft:805\n- draft:804\n- draft:803\n- draft:776\n- draft:775\n- draft:774\n- draft:773\n- draft:772\n- draft:771\n- draft:770\n- draft:769\n- draft:768\n- draft:767\n- draft:766\n- draft:765\n- draft:764\n- draft:763\n- draft:762\n- draft:761\n- draft:760\n- draft:759\n- draft:758\n- draft:757\n- draft:756\n- draft:755\n- draft:754\n', 'Batch::MetadataImport')
```

```text
E, [2015-06-22T15:36:21.976241 #31991] ERROR -- : Mysql2::Error: Data too long for column 'metadata_file' at row 1: INSERT INTO `batches` (`created_at`, `creator_id`, `job_ids`, `metadata_file`, `pids`, `type`) VALUES ('2015-06-22 15:36:21', 3, '--- []\n', '<?xml version=\"1.0\" encoding=\"UTF-8\"?><items><digitalObject><pid>draft:813</pid><datastream id=\"DCA-META\"><dc xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dcadesc=\"http://nils.lib.tufts.edu/dcadesc/\" xmlns:dcatech=\"http://nils.lib.tufts.edu/dcatech/\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"0.1\">\n  <dc:creator>Rowlandson, Thomas, 1756-1828.</dc:creator>\n  <dc:description>This engraving of an art exhibition in Somerset House was published as Plate 2 of Microcosm of London (1808). Today, Somerset House contains the art collection of the Courtauld Institute of Art, a self-governing college of the University of London specialising in the study of the history of art.</dc:description>\n  <dc:description>Location created: England.</dc:description>\n  <dc:description>Date created: c. 1787.</dc:description>\n  <dc:description>Medium: Aquatint.</dc:description>\n  <dc:description>Accession Number: 14.8502-30AM.50</dc:description>\n  <dc:publisher>Tufts University. Tisch Library.</dc:publisher>\n  <dc:source>Artifact</dc:source>\n  <dc:date.created>1787</dc:date.created>\n  <dc:type>image</dc:type>\n  <dc:format>image/tiff</dc:format>\n  <dcadesc:corpname>Somerset House (London, England)</dcadesc:corpname>\n  <dcadesc:corpname>Courtauld Institute of Art.</dcadesc:corpname>\n  <dcadesc:subject>Caricature.</dcadesc:subject>\n  <dc:rights>http://sites.tufts.edu/dca/research-help/copyright-and-citations/</dc:rights>\n  <dc:temporal>18th century.</dc:temporal>\n  <dc:title>Exhibition Room, Somerset House.</dc:title>\n</dc>
```

[ rest of repeated copy of import file omitted ]

```text
 draft:757\n- draft:756\n- draft:755\n- draft:754\n', 'Batch::MetadataImport')
D, [2015-06-22T15:36:21.976585 #31991] DEBUG -- :    (0.1ms)  ROLLBACK
I, [2015-06-22T15:36:21.976755 #31991]  INFO -- : Completed 500 Internal Server Error in 19ms
F, [2015-06-22T15:36:21.978399 #31991] FATAL -- : 
ActiveRecord::StatementInvalid (Mysql2::Error: Data too long for column 'metadata_file' at row 1: INSERT INTO `batches` (`created_at`, `creator_id`, `job_ids`, `metadata_file`, `pids`, `type`) VALUES ('2015-06-22 15:36:21', 3, '--- []\n', '<?xml version=\"1.0\" encoding
```

[ repeated import file content omitted ]

```text
</rdf:Description>\n</rdf:RDF>\n</datastream></digitalObject></items>', '---\n- draft:813\n- draft:812\n- draft:811\n- draft:810\n- draft:809\n- draft:808\n- draft:807\n- draft:806\n- draft:805\n- draft:804\n- draft:803\n- draft:776\n- draft:775\n- draft:774\n- draft:773\n- draft:772\n- draft:771\n- draft:770\n- draft:769\n- draft:768\n- draft:767\n- draft:766\n- draft:765\n- draft:764\n- draft:763\n- draft:762\n- draft:761\n- draft:760\n- draft:759\n- draft:758\n- draft:757\n- draft:756\n- draft:755\n- draft:754\n', 'Batch::MetadataImport')):
  app/controllers/batches_controller.rb:38:in `create_and_run_batch'
  app/controllers/batch/metadata_imports_controller.rb:16:in `create'


I, [2015-06-22T15:36:24.681255 #31991]  INFO -- : Started POST "/records/draft:MS210.004.001.00001.00006/publish" for 130.64.37.167 at 2015-06-22 15:36:24 +0000
I, [2015-06-22T15:36:24.682485 #31991]  INFO -- : Processing by RecordsController#publish as HTML
I, [2015-06-22T15:36:24.682542 #31991]  INFO -- :   Parameters: {"authenticity_token"=>"M7wOqu9idBuIvF9vAO+I/tIhiHxIO2Fj1KYSJhC61oM=", "id"=>"draft:MS210.004.001.00001.00006"}
D, [2015-06-22T15:36:24.683874 #31991] DEBUG -- :   User Load (0.1ms)  SELECT  `users`.* FROM `users`  WHERE `users`.`id` = 3  ORDER BY `users`.`id` ASC LIMIT 1
D, [2015-06-22T15:36:24.726611 #31991] DEBUG -- : map_model_name() has mapped info:fedora/cm:Image.4DS to info:fedora/afmodel:TuftsImage
D, [2015-06-22T15:36:24.729274 #31991] DEBUG -- :   Role Load (0.2ms)  SELECT `roles`.* FROM `roles` INNER JOIN `roles_users` ON `roles`.`id` = `roles_users`.`role_id` WHERE `roles_users`.`user_id` = 3
D, [2015-06-22T15:36:24.729476 #31991] DEBUG -- : Usergroups are ["public", "admin", "registered"]
D, [2015-06-22T15:36:24.730284 #31991] DEBUG -- :   Role Exists (0.1ms)  SELECT  1 AS one FROM `roles` INNER JOIN `roles_users` ON `roles`.`id` = `roles_users`.`role_id` WHERE `roles_users`.`user_id` = 3 AND `roles`.`name` = 'admin' LIMIT 1
D, [2015-06-22T15:36:24.731222 #31991] DEBUG -- :   User Load (0.3ms)  SELECT  `users`.* FROM `users`  WHERE `users`.`id` = 3 LIMIT 1
[mark@ip-10-141-162-81 current]$ 
```

**Comment by jcoyne** [comment]
I adjusted the length of the field with this migration: https://github.com/curationexperts/mira/blob/3708afff0a04e15ffdd9e2defc354f0846f89b97/db/migrate/20150601221522_convert_metadata_file_to_text.rb  has it been run?

**Comment by mark-dce** [comment]
There are no migrations pending (and normally they get run every deployment by capistrano).   When I checked the live database config, there doesn't seem to be a limit:

```text
mysql> show full columns from batches \g
+---------------+--------------+-----------------+------+-----+---------+----------------+---------------------------------+---------+
| Field         | Type         | Collation       | Null | Key | Default | Extra          | Privileges                      | Comment |
+---------------+--------------+-----------------+------+-----+---------+----------------+---------------------------------+---------+
| id            | int(11)      | NULL            | NO   | PRI | NULL    | auto_increment | select,insert,update,references |         |
| creator_id    | int(11)      | NULL            | YES  |     | NULL    |                | select,insert,update,references |         |
| template_id   | varchar(255) | utf8_general_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| type          | varchar(255) | utf8_general_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| pids          | text         | utf8_general_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| created_at    | datetime     | NULL            | YES  |     | NULL    |                | select,insert,update,references |         |
| job_ids       | text         | utf8_general_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| record_type   | varchar(255) | utf8_general_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| metadata_file | text         | utf8_general_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| behavior      | varchar(255) | utf8_general_ci | YES  |     | NULL    |                | select,insert,update,references |         |
+---------------+--------------+-----------------+------+-----+---------+----------------+---------------------------------+---------+
```

**Comment by jcoyne** [comment]
Hmm: 

> The type TEXT is limited to 2^16 bytes, or 65536 bytes. Try using the type LONGTEXT instead. It can hold values up to 2^32 bytes in length.

from http://stackoverflow.com/questions/2569838/mysql-data-type-text-erroring-data-too-long

**Comment by mark-dce** [comment]
The import file is 110420 characters long.

**Comment by mark-dce** [comment]
Normalizing a large group of records is likely to be this big or bigger - would it make sense to store the files outside the database?

**Comment by jcoyne** [comment]
It appears we need to set the `limit: 2**32 - 1` on that migration. Then it will use the `LONGTEXT` type.

**Comment by mark-dce** [comment]
see: Storage Requirements for String Types
http://dev.mysql.com/doc/refman/5.5/en/storage-requirements.html
