### ISSUE TITLE
Fix CI Ldap errors

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/MIRA#67]
Look at running ladle for CI
https://github.com/NUBIC/ladle
OR see if we can remove dependencies on LDAP from the test suite.

**EXAMPLE ERROR**
```
     7.2) Failure/Error: let(:generic) { TuftsGenericObject.create!(title: 'My title2', edit_users: [user.display_name], displays: ['dl']) }

          Net::LDAP::Error:
            Server localhost refused connection on port 3389.
          # /Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/net-ldap-0.11/lib/net/ldap/connection.rb:17:in `rescue in initialize'
          # /Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/net-ldap-0.11/lib/net/ldap/connection.rb:12:in `initialize'
          # /Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/net-ldap-0.11/lib/net/ldap.rb:1223:in `new'
          # /Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/net-ldap-0.11/lib/net/ldap.rb:1223:in `new_connection'
          # /Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/net-ldap-0.11/lib/net/ldap.rb:1209:in `use_connection'
          # /Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/net-ldap-0.11/lib/net/ldap.rb:742:in `block in search'
          # /Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/net-ldap-0.11/lib/net/ldap/instrumentation.rb:19:in `instrument'
          # /Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/net-ldap-0.11/lib/net/ldap.rb:741:in `search'
          # /Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/net-ldap-0.11/lib/net/ldap.rb:1128:in `search_root_dse'
          # /Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/net-ldap-0.11/lib/net/ldap.rb:1194:in `paged_searches_supported?'
          # /Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/net-ldap-0.11/lib/net/ldap.rb:734:in `search'
          # /Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/devise_ldap_authenticatable-0.8.5/lib/devise_ldap_authenticatable/ldap/connection.rb:190:in `search_for_login'
          # /Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/devise_ldap_authenticatable-0.8.5/lib/devise_ldap_authenticatable/ldap/connection.rb:59:in `ldap_param_value'
          # /Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/devise_ldap_authenticatable-0.8.5/lib/devise_ldap_authenticatable/ldap/adapter.rb:76:in `get_ldap_param'
          # /Users/mark/.rvm/gems/ruby-2.3.4@mira/bundler/gems/tufts_concerns-3098250cc7b5/app/models/user.rb:70:in `display_name'
          # ./spec/controllers/attachments_controller_spec.rb:23:in `block (4 levels) in <top (required)>'
          # ./spec/controllers/attachments_controller_spec.rb:25:in `block (4 levels) in <top (required)>'
          # ------------------
          # --- Caused by: ---
          # Errno::ECONNREFUSED:
          #   Connection refused - connect(2) for "localhost" port 3389
          #   /Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/net-ldap-0.11/lib/net/ldap/connection.rb:13:in `initialize'
```

**Comment by mark-dce** [comment]
Fixed by #80
